### ISSUE TITLE
Package conflict with Laravel email verification 

### ISSUE THREAD

**Issue by bm2ilabs** [josiasmontag/laravel-localization#1]
Hello, Thank you for this package .
I have noticed when i add this package to the latest Laravel version (5.7) i get error when i try to register new user ,

``php
call_user_func() expects parameter 1 to be a valid callback, no array or string given
``

 i track down the error to the **keyresolver** in the **URL** generator of laravel , the keyresolver always return **null** that what cause the issue .

**Comment by bsh** [comment]
Same problem.

**Comment by josiasmontag** [comment]
Tagged `0.4.4` that should solve the problem

**Comment by bsh** [comment]
![image](https://user-images.githubusercontent.com/374377/48300432-909e5100-e4dd-11e8-8508-3da5f075365e.png)

**Comment by josiasmontag** [comment]
Try again (0.4.5)

**Comment by bsh** [comment]
It works. Thank you!
