### ISSUE TITLE
getLocaleUrl does not work with "hide_default_locale_in_url" => false

### ISSUE THREAD

**Issue by rolandstarke** [josiasmontag/laravel-localization#4]
Hey :)

```blade
@if(Localization::isLocalizedRoute())
    @foreach(Localization::getLocales() as $localeCode => $properties)
        <link rel="alternate" hreflang="{{ $localeCode }}" href="{{ Localization::getLocaleUrl($localeCode) }}">
    @endforeach
@endif
```

results in:
```html
<link rel="alternate" hreflang="en" href="http://127.0.0.1:8000/de/watch/4J9EzCCU22AlQY">
<link rel="alternate" hreflang="de" href="http://127.0.0.1:8000/de/watch/4J9EzCCU22AlQY">
```

note that its 2 times the same url.

**config**
app default locale: `"en"`,
visited page locale: `"de"`,
hide locale in url: `false`
the rest of the params all false or null

I threw some `var_dump`s in: `Localization::getLocaleUrl('en')` seaches for `en.index` but only `de.index` and `index` are registered as routes.

**Comment by josiasmontag** [comment]
Thanks, for the report.
Can you check if the latest commit ([#5bb9b4e](https://github.com/josiasmontag/laravel-localization/commit/5bb9b4e1f0135d32701b82dd7871e81f50a9b4b5)) solves the issue?

**Comment by rolandstarke** [comment]
Hey, yes the issue is gone with this change.
