### ISSUE TITLE
Question about the config file

### ISSUE THREAD

**Issue by parnissolle** [josiasmontag/laravel-localization#6]
Hey, what's the exact purpose of `script ` key in the config file?

```php
...
'en' => ['name' => 'English', 'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
...
```

**Comment by josiasmontag** [comment]
Nothing, the only used keys are `name` and `domain`. We should fix the README / example config.

**Comment by parnissolle** [comment]
Ok. Thanks 🙂
