### ISSUE TITLE
How we use form post method

### ISSUE THREAD

**Issue by officialmmt** [josiasmontag/laravel-localization#7]
Hi, I am trouble with post methods with other languages. It give all the time 'The GET method is not supported for this route. Supported methods: POST.'. I tried inside and outside localizedRoutesGroup route group result is the same.  What I have to do for fix?

**Comment by josiasmontag** [comment]
How does your routes file look like? I don't think the issue is related to this package.

**Comment by officialmmt** [comment]
Localization::localizedRoutesGroup(function() {
    Route::get('/', 'ServiceController@getindex')->name('index');
   Route::post('postmain', 'ServiceController@postindex')->name('postindex');
});
It is like usually.

**Comment by josiasmontag** [comment]
I cannot reproduce this, I'm thinking there is something wrong in your app that is not related to this package.

**Comment by officialmmt** [comment]
What kind of I just have a form with laravelcollective may it have affected that.
