### ISSUE TITLE
Laravel 8.0 Support

### ISSUE THREAD

**Issue by meyer59** [josiasmontag/laravel-localization#8]
Hello,

Laravel 8.0 is out now,

do you plan to support it ?

thanks.

**Comment by josiasmontag** [comment]
Laravel 8 is already supported.

**Comment by meyer59** [comment]
I am following the laravel upgrade guide and when i ran composer update a got this error:
`- josiasmontag/laravel-localization 0.6.2 requires laravel/framework ^6.0|^7.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.0)`

**Comment by josiasmontag** [comment]
You need to use the latest version `0.8.2`.
